# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://oort77.github.io/nb_dev/"

git_url = "https://github.com/oort77/nb_dev/tree/master/"

def custom_doc_links(name): return None
